# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f46411eccc6cafa72ca1de007afbbb69f2adb42cf98f7ceb6e77a25ce052ef51a7aeb169f64325f0468481041b327fe2b3aca797da20ee40e7f4270d5395189

test:
  secret_key_base: 47f1c3de45d81d3ba68d21b4cd9b3c2c90a16b75971ad39bbaf46eda0727daaf5643c2739fe425f7bc4dc38db75f42225294adf561d349c166ba56da9a62cf85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
